Statistics ilai
sufka861/AB-test pull request #31
Opened 2023-02-23 17:06 UTC by ilaiazulay

2023-02-23 18:18 UTC, peerfikhman requested changes
Hey @ilaiazulay,
I reviewed your code, very good job!
There are  though some conventions that we must follow such as working on the data base through the Repositories and not directly on the model, I very much advise to fix it before merge.

Regarding the crone job, please checkout my comments,
I advise to consult with @AtomicManic and @sufka861 about the way of doing this,
I haven't put my mind into the correct solution but I think that saving each month's statistics in the data base is much more advised then doing a cron job every month and resetting the data resulting in loosing that data.

2023-02-23 18:18 UTC, peerfikhman commented on controller/stats.controller.js
> +const Experiment = require("../models/Experiment.model");
same as before it is advised to creat a method in repository and only use the repository

2023-02-23 18:18 UTC, peerfikhman commented on controller/stats.controller.js
> +    if (!mongoose.isValidObjectId(accountID)) throw new ValidationError.MissingPropertyError("account ID");
Great Validation!

2023-02-23 18:18 UTC, peerfikhman commented on controller/stats.controller.js
> +    Experiment.aggregate([
Very nice logic in this function and a very elegant way of coding
though this should not be here, this should be in the Experiment Repository as mentioned above

2023-02-23 18:18 UTC, peerfikhman commented on Service/cron.job.js
> +    console.log("Monthly call count reset successful");
although you are correct that we should log this data, console log is no the way of doing this

2023-02-23 18:18 UTC, peerfikhman commented on Service/cron.job.js
> +    console.error(err);
errors should be handled with error handlers

2023-02-23 18:18 UTC, peerfikhman commented on router/stats.router.js
> +statsRouter.get('/testsPerMonth/:accountId',statsController.getTestsPerMonth);
good job on the Router very nice looking

2023-02-24 07:50 UTC, AtomicManic commented on Service/cron.job.js
> +cron.schedule("0 0 1 * *", async () => {
Read some of the comments, what Peer is suggesting is correct. Better make a collection of data logs and take it from there per call

2023-02-24 08:26 UTC, peerfikhman approved these changes
Good job on the fixes!
Merge approved!

2023-02-24 08:26 UTC, merged